services:

  frontend:
    image: ${FRONTEND_IMAGE:-frontend-local:latest}
    ports:
      - "80:80"
    restart: always
    depends_on:
      - backend

  backend:
    image: ${BACKEND_IMAGE:-backend-local:latest}
    restart: always
    expose:
      - "8000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/airbnb_listing
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    restart: always
    volumes:
      - mongo_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d

volumes:
  mongo_data: